// <auto-generated />
using System;
using DanaBet.DBData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanaBet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251021214819_update-db")]
    partial class updatedb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DanaBet.DBModel.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TBL_Games");
                });

            modelBuilder.Entity("DanaBet.DBModel.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxUserCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("TBL_Leagues");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeagueLevelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueLevelsId");

                    b.ToTable("TBL_LeagueGroups");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueGroupsUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueGroupId");

                    b.HasIndex("LeagueUserId");

                    b.ToTable("TBL_LeagueGroupsUsers");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueLevels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("TBL_LeagueLevels");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueScores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueGroupUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeagueGroupsUsersId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxUserCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeagueGroupsUsersId");

                    b.ToTable("TBL_LeagueScores");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("TBL_LeagueUsers");
                });

            modelBuilder.Entity("DanaBet.DBModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TBL_Users");
                });

            modelBuilder.Entity("DanaBet.DBModel.League", b =>
                {
                    b.HasOne("DanaBet.DBModel.Game", "Games")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Games");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueGroup", b =>
                {
                    b.HasOne("DanaBet.DBModel.LeagueLevels", "LeagueLevels")
                        .WithMany()
                        .HasForeignKey("LeagueLevelsId");

                    b.Navigation("LeagueLevels");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueGroupsUsers", b =>
                {
                    b.HasOne("DanaBet.DBModel.LeagueGroup", "LeagueGroups")
                        .WithMany()
                        .HasForeignKey("LeagueGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DanaBet.DBModel.LeagueUser", "LeagueUser")
                        .WithMany()
                        .HasForeignKey("LeagueUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueGroups");

                    b.Navigation("LeagueUser");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueLevels", b =>
                {
                    b.HasOne("DanaBet.DBModel.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueScores", b =>
                {
                    b.HasOne("DanaBet.DBModel.LeagueGroupsUsers", "LeagueGroupsUsers")
                        .WithMany()
                        .HasForeignKey("LeagueGroupsUsersId");

                    b.Navigation("LeagueGroupsUsers");
                });

            modelBuilder.Entity("DanaBet.DBModel.LeagueUser", b =>
                {
                    b.HasOne("DanaBet.DBModel.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });
#pragma warning restore 612, 618
        }
    }
}
